version: "3.7"

services:
  redis:
    image: "redis"
    ports:
     - "6001:6379"

  server:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - redis
    command: "rake server"

  rloop:
    build: .
    depends_on:
      - server
    command: "rake rloop"