version: "3.7"

services:
  redis:
    image: "redis"
    ports:
     - "6000:6379"
    restart: on-failure

  setup:
    build:
      context: .

  server:
    image: "clear_cache_setup"
    ports:
      - "4567:4567"
    depends_on:
      - "setup"
    restart: on-failure
    command: "rake server"

  rloop:
    image: "clear_cache_setup"
    depends_on:
      - "setup"
    env_file:
      - ./tokens.env
    restart: on-failure
    command: "rake rloop"