version: "3.7"

services:
  redis:
    image: "redis"
    ports:
     - "6000:6379"

  setup:
    build:
      context: .

  server:
    image: clear_cache_setup
    ports:
      - "4567:4567"
    depends_on:
      - setup
    command: "rake server"

  rloop:
    image: clear_cache_setup
    depends_on:
      - setup
    command: "rake rloop"