version: "3.7"

services:
  redis:
    image: "redis"
    ports:
     - "6000:6379"

  server:
    build:
      context: .
      dockerfile: Docker_server
      # args:
      #   buildno: 1
    ports:
      - "4567:4567"
    depends_on:
      - redis
    command: "rake server"

  rloop:
    build:
      context: .
      dockerfile: Docker_rloop
    depends_on:
      - server
    command: "rake rloop"